version: 0.2

phases:
  install:
    commands:
      - echo INSTALL Commands ------------------------------------------------
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo PRE BUILD Commands ----------------------------------------------
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo BUILD Commands --------------------------------------------------
      - echo testing .net classic tgimba
      - ls
      - rm -rf BucketListDataProvider
      - rm -rf CommonServiceCode
      - rm DashboardSQL.sql
      - rm -rf Driver
      - rm -rf MemberShip
      - rm -rf MobileWebsite
      - rm -rf Services
      - rm -rf Shared
      - rm TGIMBA.sln
      - rm -rf Tests
      - ls
      - cp -r TgimbaWeb/* .
      - rm -rf TgimbaWeb
      - ls
      - npm install
      - npm run ftpLogin
      - npm run verifyDeploy
  post_build:
    commands:
      - echo POST BUILD Commands ---------------------------------------------
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'